### ISSUE TITLE
Problem with "Toggle hide all CC lanes except lane under mouse cursor/last clicked..."

### ISSUE THREAD

**Issue by SoliDeoGloria2** [Jeff0S/sws#705] opened 2015-03-11 15:52 UTC
Hi!

When using these actions with shortcuts, one after the other : 

-"Show only used CC lanes"
and then
-Any of the "Toggle hide all CC lanes except lane under mouse curor/last clicked (set height to....) or "Hide all CC lanes except lane under mouse cursor/last clicked" actions 

The hide actions, most of the times, don´t work as expected; they show another set of stacked CC lanes. Only the second time I use it does the function perform as expected, showing the focused lane. Sometimes the desired lane to focus won´t appear when the "new" set of lanes is shown on the first try.

I hope it´s something related to any particular setting, but I report it anyway because these are extremely useful, everyday actions in my workflow.

Thank you very much in advance.

**Comment by Breeder** [comment] 2015-03-14 03:28
After private conversation, it seems that SoliDeoGloria2 was using REAPER 5 pres which had a bug with certain CC lanes that is fixed in current pre (v5pre17) (reported here: http://forum.cockos.com/showthread.php?p=1466047#post1466047)

I'm not quite sure what else could be the cause of this because the code is not that complicated (VELLANE lines in chunk are saved and restored without any editing done to them).

Part of the report that says that the action works after the second time confirms this suspicion (first time the action is run, lanes are wrongly replaced by REAPER - so the second time there are no lanes that show buggy behavior) 

I'm closing the issue as resolved for now, let us know if the bug reappears

**Closed by Breeder** 2015-03-14 03:28 UTC

**Comment by StephanRoemer** [comment] 2019-01-31 18:34
Yes, the bug re-appeared. Executing the command adds a 4th CC lane here. I have to figure out the behaviour.
